# Generated by Django 6.0.2 on 2026-02-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temp', models.FloatField(max_length=100)),
                ('humidity', models.IntegerField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
